# -*- coding: utf-8 -*-
"""VISDAT_FINAL_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fTexW06rNFDg8rnR8GN3vY05vieg2HuR

### LIBRARIES
"""
import pandas as pd
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.models import CategoricalColorMapper
from bokeh.palettes import Spectral6,Colorblind8
from bokeh.layouts import widgetbox, row, gridplot
from bokeh.models import Slider, Select
from bokeh.io import show

data = pd.read_csv("covid_19_indonesia_time_series_all.csv")
data.info()

data = data.rename(columns={'Date': 'date', 
                        'Location ISO Code': 'location_iso_code', 
                        'Location': 'location', 
                        'New Cases': 'new_cases', 
                        'New Deaths': 'new_deaths',
                        'New Recovered': 'new_recovered', 
                        'New Active Cases': 'new_active_cases', 
                        'Total Cases': 'total_cases', 
                        'Total Deaths': 'total_deaths',
                        'Total Recovered': 'total_recovered', 
                        'Total Active Cases': 'total_active_cases', 
                        'Location Level': 'location_level',
                        'City or Regency': 'city_or_regency', 
                        'Province': 'province', 
                        'Country': 'country', 
                        'Continent': 'continent', 
                        'Island': 'island',
                        'Time Zone': 'time_zone', 
                        'Special Status': 'special_status', 
                        'Total Regencies': 'total_regencies', 
                        'Total Cities': 'total_cities',
                        'Total Districts': 'total_districts', 
                        'Total Urban Villages': 'total_urban_villages', 
                        'Total Rural Villages': 'total_rural_villages',
                        'Area (km2)': 'area_(km2)', 
                        'Population': 'population', 
                        'Population Density': 'population_density', 
                        'Longitude': 'longitude',
                        'Latitude': 'latitude', 
                        'New Cases per Million': 'new_cases_per_million', 
                        'Total Cases per Million': 'total_cases_per_million',
                        'New Deaths per Million': 'new_deaths_per_million', 
                        'Total Deaths per Million': 'total_deaths_per_million',
                        'Total Deaths per 100rb': 'total_deaths_per_100rb', 
                        'Case Fatality Rate': 'case_fatality_rate', 
                        'Case Recovered Rate': 'case_recovered_rate',
                        'Growth Factor of New Cases': 'growth_factor_of_new_cases', 
                        'Growth Factor of New Deaths': 'growth_factor_of_new_deaths'})

# data['date'] = pd.to_datetime(data['date'])

data['year'] = 2020

# data['DateString'] = data['DateString'].astype(float)

data.head()

data.set_index('year', inplace=True)

data.info()

data = data.loc[:,['date','location','total_cases','total_deaths','province','population','island','continent','new_cases','new_deaths','total_active_cases']]

data.head()

data.dropna(how="any",inplace = True)
data.info()

data

# Make a list of the unique values from the region column: regions_list
province_list = data.province.unique().tolist()

# island_list = data.island_unique.unique().tolist()

# island_list

color_mapper = CategoricalColorMapper(factors=province_list, palette=Colorblind8)

source = ColumnDataSource(data={
    # 'x'       : data.loc[1970].fertility,
    "x"                : data.loc[2020].date,
    "y"                : data.loc[2020].total_cases,
    "province"         : data.loc[2020].province,
    "pop"              : data.loc[2020].population,
    "island"           : data.loc[2020].island,
})

# Create the figure: plot
plot = figure(title='Covid-19 Indonesia', x_axis_label='Date', y_axis_label='Total Kasus',
           plot_height=400, plot_width=700, tools=[HoverTool(tooltips='@x|@y|@province')])

plot.circle(x='x', y='y', source=source, fill_alpha=0.8,
           color=dict(field='island', transform=color_mapper), legend='island')

plot.legend.location = 'top_left'

def update_plot(attr, old, new):
    # set the `yr` name to `slider.value` and `source.data = new_data`
    yr = 2020
    x = x_select.value
    y = y_select.value
    # Label axes of plot
    plot.xaxis.axis_label = x
    plot.yaxis.axis_label = y
    # new data
    new_data = {
    'x'             : data.loc[yr][x],
    'y'             : data.loc[yr][y],
    'province'      : data.loc[yr].province,
    'pop'           : data.loc[yr].population,
    'island'        : data.loc[yr].island,

    }
    source.data = new_data
    
    # Add title to figure: plot.title.text
    plot.title.text = 'Covid-19 data pulau %d' % yr

# slider = Slider(start=1970, end=2022, step=1, value=2020, title='Year')
# slider.on_change('value',update_plot)

# data.index.to_list()

# island_unq = data.index.unique()

# is_list = island_unq.to_list()
# Make dropdown menu for x and y axis
# Create a dropdown Select widget for the x data: x_select
# Make dropdown menu for x and y axis
# Create a dropdown Select widget for the x data: x_select
# select_island = Select(
#     options= [island_unq[0],island_unq[1],island_unq[2],island_unq[3],island_unq[4],island_unq[5],island_unq[6]],
#     value= 'Jawa',
#     title='Pulau Indonesia'
# )

# Attach the update_plot callback to the 'value' property of x_select
# select_island.on_change('value', update_plot)

# Make dropdown menu for x and y axis
# Create a dropdown Select widget for the x data: x_select
x_select = Select(
    options=['total_deaths', 'total_cases', 'new_cases', 'new_deaths'],
    value='total_cases',
    title='x-axis data'
)

x_select.on_change('value', update_plot)

y_select = Select(
    options=['total_deaths', 'total_cases', 'new_cases', 'new_deaths'],
    value='total_cases',
    title='y-axis data'
)

# Attach the update_plot callback to the 'value' property of y_select
y_select.on_change('value', update_plot)

# Create layout and add to current document
layout = row(widgetbox(x_select, y_select), plot)
curdoc().add_root(layout)

# show(layout)